apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pihole
  namespace: pihole
spec:
  interval: 30m
  chart:
    spec:
      chart: pihole
      version: "2.*"
      sourceRef:
        kind: HelmRepository
        name: mojo2600
        namespace: flux-system

  values:
    # Basic settings
    timezone: "Europe/Athens"
    admin:
      existingSecret: pihole-secret  # uses key WEBPASSWORD

    # Upstream resolvers (you can change later)
    DNS1: "1.1.1.1"
    DNS2: "1.0.0.1"

    # ---- Persistence ----
    persistence:
      enabled: true
      # If you have a default storageclass, leave this blank.
      # Otherwise specify one, e.g. local-path / longhorn
      # storageClass: "local-path"
      size: 1Gi

    # ---- Services ----
    # Web UI stays ClusterIP; we route it with an internal HTTPRoute below.
    serviceWeb:
      type: ClusterIP
      port: 80

    # DNS needs TCP and UDP 53 on a LoadBalancer with a fixed IP from your LAN.
    # Cilium L2 IPAM uses this annotation to assign the IP.
    serviceDns:
      type: LoadBalancer
      # Optional: give the LB service an explicit name (defaults to 'dns')
      # name: dns
      annotations:
        io.cilium/lb-ipam-ips: "192.168.31.244"   # <— choose a free IP in your LAN
      externalTrafficPolicy: Local
      # expose both protocols
      ports:
        - port: 53
          protocol: UDP
          targetPort: 53
          name: dns-udp
        - port: 53
          protocol: TCP
          targetPort: 53
          name: dns-tcp

    # ---- Extra config for conditional forwarding ----
    extraVolumes:
      - name: custom-dnsmasq
        configMap:
          name: pihole-dnsmasq-custom
    extraVolumeMounts:
      - name: custom-dnsmasq
        mountPath: /etc/dnsmasq.d/05-k8s-conditional.conf
        subPath: 05-k8s-conditional.conf
        readOnly: true

---
apiVersion: v1
kind: Namespace
metadata:
  name: pihole