apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: pihole-admin
  namespace: pihole
spec:
  hostnames:
    - pihole.glamprinakis.com
  parentRefs:
    - name: cilium-gateway-internal
      namespace: kube-system
  rules:
    - backendRefs:
        - name: pihole-web
          port: 80