---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pihole
  namespace: pihole
spec:
  interval: 30m
  chart:
    spec:
      chart: pihole
      version: "2.34.0"
      sourceRef:
        kind: HelmRepository
        name: mojo2600
        namespace: flux-system
  values:
    # Basic settings
    timezone: "Europe/Athens"

    # Admin password
    adminPassword: "changeme123"

    # DNS settings
    DNS1: "1.1.1.1"
    DNS2: "1.0.0.1"
    
    # Custom dnsmasq configuration for Kubernetes cluster domains
    dnsmasq:
      customDnsEntries: []
      customCnameEntries: []
      customSettings:
        # Forward .cluster.local domains to CoreDNS
        - "server=/cluster.local/10.43.0.10"
        - "server=/svc.cluster.local/10.43.0.10"
        - "server=/default.svc.cluster.local/10.43.0.10"

    # Persistence - disabled for now due to no storage class
    persistentVolumeClaim:
      enabled: false

    # Web service (ClusterIP for internal access via Gateway)
    serviceWeb:
      type: ClusterIP
      port: 80

    # DNS service with LoadBalancer for both TCP and UDP
    serviceDns:
      type: LoadBalancer
      externalTrafficPolicy: Local
      loadBalancerIP: "192.168.31.244"
      annotations:
        io.cilium/lb-ipam-ips: "192.168.31.244"
      # Combine both TCP and UDP on same service
      mixedService: true
