---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana
  namespace: grafana
spec:
  interval: 30m
  chart:
    spec:
      chart: grafana
      version: "8.7.1"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  values:
    # Basic settings
    adminUser: admin
    adminPassword: "${SECRET_GRAFANA_ADMIN_PASSWORD}"

    # Service configuration
    service:
      type: ClusterIP
      port: 80

    # Enable persistence (we'll disable it like Pi-hole for now)
    persistence:
      enabled: false

    # Grafana configuration
    grafana.ini:
      server:
        domain: "grafana.${SECRET_DOMAIN}"
        root_url: "https://grafana.${SECRET_DOMAIN}"
      security:
        admin_user: admin
