apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:H4wgKr8IpEkHHagEJdIh8w==,iv:bZmfwy5cRr2ZDR0bA8iItiiDj3/5JQFYR6j+U3Jep/Y=,tag:HnJlG0buyWJxCdKfLtWm6A==,type:str]
sops:
  age:
    - recipient: age1zv85xganrszfh5syhz237f3gvhlvjek2y7llrpwv8tf0wqjzyqsqugj9lh
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYYlRTa3NDamIwYnNGZVdV
        UlVnRHNCdllrRFRtcDQxaXg0UDQ1VlhLNUhVCmNKS0hvakR5d21iZnE5c0dRZjZH
        ekhncWVYbmdnQitzV0d5M1p3TVR3ZFEKLS0tIEZ3YjNnNnBhQWtqYllwSnZmeHYv
        Z1FPSDUrSHRWTmxLa3lUaXVSR0xReGcKYV+RhmaOFTUJlSniL7XWd+Lh6jSKGQUg
        k2BatPin3Z3s98GT4hB13UQSPRkDWtVnnWwPafIezpLRdz7Q+93NHw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-08-29T12:54:55Z"
  mac: ENC[AES256_GCM,data:rOCFSQaLXI67VNYzI2Zl9pS0dIfs7nxFIdL1z3Ef+OQCymzAbpL6HHtRBCx2MXJUqFd+daQsk9GixiDY2onUXW70nL2FsmjL+HSQeZkZrbqfF3gTZKqLg8KhV4p+DRdXqLrrqKNlUZo5HwJFteDx6eMd/VKFWI72wP0/XAjZ+YQ=,iv:Jj7UQIPp7Qvs5rUwk8taosDW4cqDb4NoblFqurAJEyU=,tag:rPu3FzUGRhO6aVKFmGd1Aw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
